default: &default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_bin
  pool: <%= ENV.fetch("DATABASE_POOL") { 25 } %>
  host: <%= ENV["DATABASE_HOSTNAME"] %>
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  port: 3306
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database:  blog-api_development

staging:
  <<: *default
  database:  blog-api_staging

test:
  <<: *default
  database:  blog-api_test

production:
  <<: *default
  database: <%= ENV["DATABASE_NAME"] %>
