#!/bin/bash
set -e
bundle check || bundle install --binstubs="$BUNDLE_BIN"

bundle exec rails db:create
bundle exec rails db:migrate

rm -f tmp/pids/server.pid
bundle exec rails s -b 0.0.0.0 -p 3000

exec "$@"
